version: '3.8'

services:
  # NGINX Proxy Manager
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin panel
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy_net

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=supersecurepassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    volumes:
      - ./nextcloud_data:/var/www/html
    networks:
      - proxy_net

  db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=evenmoresecure
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecurepassword
    volumes:
      - ./nextcloud_db:/var/lib/mysql
    networks:
      - proxy_net

  # Home Assistant
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./homeassistant_config:/config
    network_mode: host   # Necesario para detección de dispositivos
    restart: unless-stopped

  # Plex
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host   # Para DLNA y LAN discovery
    environment:
      - PLEX_CLAIM=your_plex_claim_token  # Puedes dejarlo vacío si no tienes uno
      - ADVERTISE_IP=http://your-server-ip:32400/
    volumes:
      - ./plex_config:/config
      - ./plex_transcode:/transcode
      - ./plex_media:/data
    restart: unless-stopped

  # Retroarch (experimental)
  retroarch:
    image: libretro/retroarch:latest
    container_name: retroarch
    ports:
      - "55355:55355"  # Si expone interfaz web o TCP
    volumes:
      - ./retroarch_config:/config
    networks:
      - proxy_net
    restart: unless-stopped

networks:
  proxy_net:
    external: true
