version: '3.8'

services:
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # Si usarás HTTPS más adelante
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - nextcloud
      - homeassistant
      - plex
      - retroarch
    restart: always

  nextcloud:
    image: nextcloud:latest
    depends_on:
      - db_nextcloud
    environment:
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db_nextcloud
    volumes:
      - nextcloud_data:/var/www/html
    restart: always

  db_nextcloud:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db_nextcloud_data:/var/lib/mysql
    restart: always

  homeassistant:
    image: homeassistant/home-assistant:stable
    volumes:
      - ./homeassistant_config:/config
    network_mode: host
    restart: always

  plex:
    image: plexinc/pms-docker:latest
    environment:
      - PLEX_CLAIM=claim-token
      - ADVERTISE_IP=http://your-server-ip:32400/
    network_mode: host
    volumes:
      - ./plex_config:/config
      - ./plex_transcode:/transcode
      - ./plex_media:/data
    restart: always

  retroarch:
    image: libretro/retroarch:latest
    # Este contenedor es más experimental, ajusta según uso real
    ports:
      - "55355:55355"
    volumes:
      - ./retroarch_config:/config
    restart: always

volumes:
  nextcloud_data:
  db_nextcloud_data:
