# ==========================
# Redes
# ==========================
networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge

# ==========================
# Servicios
# ==========================
services:

  # ==========================
  # Nginx Proxy Manager
  # ==========================
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ${DATA_PATH}/npm/data:/data
      - ${DATA_PATH}/npm/letsencrypt:/etc/letsencrypt
    networks:
      - default

  # ==========================
  # Portainer
  # ==========================
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/portainer_data:/data
    networks:
      - default

  # ==========================
  # Watchtower (auto-updates)
  # ==========================
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  # ==========================
  # MariaDB (Nextcloud DB)
  # ==========================
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DATA_PATH}/nextcloud_db:/var/lib/mysql
    networks:
      - default

  # ==========================
  # Nextcloud
  # ==========================
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: nextcloud-db
    volumes:
      - ${DATA_PATH}/nextcloud_html:/var/www/html
      - ${DATA_PATH}/nextcloud_config:/var/www/html/config
      - ${DATA_PATH}/nextcloud_data:/var/www/html/data
    networks:
      - default
    ports:
      - "8180:80"

  # ==========================
  # Retroarch (⚠️ comentado, revisar imagen)
  # ==========================
  #retroarch:
  #  image: es20490446e/retroarch-web
  #  container_name: retroarch
  #  restart: unless-stopped
  #  networks:
  #    - default
