name: Deploy Container
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Esta es la máquina donde se ejecuta el job
    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Clona el código fuente del repositorio
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usa el secreto SSH creado
          
      - name: Connect to Ubuntu Server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no vic@192.168.0.151 'bash -s' Script-DeployContainers.sh
