name: Deploy Terraform 2
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      -- name: Create SSH Tunnel to Docker Daemon
        run: |
          ssh -o StrictHostKeyChecking=no -p 5122 -N -L 2375:/var/run/docker.sock deploy@sylvahabitat.duckdns.org &
          # Añade el esquema 'tcp://' para que Terraform lo reconozca
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV
          echo "DOCKER_TLS_VERIFY=0" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
